#!/usr/bin/env bash

read_char() 
{
  stty -icanon -echo
  eval "$1=\$(dd bs=1 count=1 2>/dev/null)"
  stty icanon echo
}

massege= "'$*'"

git status
git add -A
git status

echo "commit msg:"

read msg

git commit -m "$msg"

echo "type q to quit, p to push"

read_char input

if [[ "$input" == "q" ]]; then
	exit
fi

if [[ "$input" == "p" ]]; then
  echo "pushing ..."
  git push
fi

echo "good job"
# motivate
read_char input
clear